class Constants {
  final INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
  final JWT_EXPIRED_ERROR = "JWT_EXPIRED_ERROR";
  final NO_ERROR = "NO_ERROR";
  final UNKNOWN_ERROR = "UNKNOWN_ERROR";
  final JWT_ERROR = "JWT_ERROR";
  final JWT_NOT_FOUND = "JWT_NOT_FOUND";
  final INVALID_STRATEGY = "INVALID_STRATEGY";
  final DIO_ERROR = "DIO_ERROR";

  final AUTH_WITH_JWT_SUCCEED = "AUTH_WITH_JWT_SUCCEED";
  final AUTH_WITH_JWT_FAILED = "AUTH_WITH_JWT_FAILED";

  final BOTH_CLIENT_AUTHED = "BOTH_CLIENT_AUTHED";
  final ONE_OR_BOTH_CLIENT_NOT_AUTHED = "ONE_OR_BOTH_CLIENT_NOT_AUTHED";
}
